language: java
jdk: oraclejdk8
#after_success:
#- mvn clean test jacoco:report coveralls:report
addons:
  sonarqube:
    token:
      secure: jxxTT5wv/YLh1l5h/GRenjFHRAPm7wegQdXS6LAqY6QlWSb8ggF5pTzLWWW1KGiYgTPCTiGaouQyVgubJ0i1x3JAmoTDGZoXPnHqCQhZ+bSM2rQOXTb0QlfVq5dbrpd31DW282tlqNoRxCl4Z8IlMYTSPLoRtT0521CsONz8ngMJyu7W3m3AQTQCZwh/4pkFiKYec925DVMoiaeJLlSrDgwRTsc2aWTt/u64Xyc2aQkaURNfl9fHxOT/y5Fw8HIcipynHgPPPM4wKxeuNPKYCGuUg7WVl2rVrCN+DuszUwKROZSAx2QJCJWgTp27yCQM/coWw/xC250ejg6h1lWf3yml7LlRY/OLGAAeNNhIiMV2CeKqdU+xrNtYVmFbmfccgGrCGrCCRQRlwlvezkhW2CKrvmBt+Kie6iCmR33ZFsWgG4bmG4uxTWF9zvBS5scDaljpm/MjmKi/PlBHhh/Qju/LcvwbwUDTmNac3pKxdQKm0hgZhmXgFJmj6/VDZEYbl+kw0ajydKxXfe3XniSHXhHX6OPD4Y+pN3shvtQyxmlk7Opmp7vnOkgiQzf7G6TxGyW1iJ4i0qcXQJl2zdi+Wn1UVLG9oSYod4wEF/Bm+0TH7nCW105p8DbY9oj1ese8PnGQU8fHnZxEkqalWXk0qzQMBozW3JK4Lx3TXqIV/WA=
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean test jacoco:report coveralls:report install sonar:sonar